### ISSUE TITLE
Invalid links to *Identicon* by *Florian Körner* in playground

### ISSUE THREAD

**Issue by KaKi87** [DiceBear/avatars#387]
Hello,

All 4 links to *Identicon* by *Florian Körner* there :

| [Playground \| DiceBear](https://www.dicebear.com/playground/?style=identicon) | [Identicon \| DiceBear](https://www.dicebear.com/styles/identicon/) |
| --- | --- |
| ![](https://github.com/dicebear/dicebear/assets/21284089/a4b83365-a1ac-4d33-9607-86e22ade64f4) | ![](https://github.com/dicebear/dicebear/assets/21284089/f6c8eb97-59ab-4521-abf7-367a937b0f28) |

Point to https://dicebear.com/ instead of the original project and author pages.

Thanks

**Comment by FlorianKoerner** [comment]
Hi, what links did you expect to find here? I think the license text here is misleading because there is no real source of the design. It's just randomly arranged pixels.

**Comment by KaKi87** [comment]
Hi,

As mentioned, I'm expecting a link to you, and a link to your original project.

Also, why are you saying *random* while it's hash-based ?

**Comment by FlorianKoerner** [comment]
DiceBear is the right link in both cases. I am the maintainer of DiceBear and have no other website.

At the same time, there is no original project. Identicons are not new in themselves, but in the end it is not a design, because of the purely optically randomly arranged pixels.

That's why the avatar style is also CC0 licensed. No copyright.

**Comment by KaKi87** [comment]
Well, then, the phrases "based on" and "remix of" should be removed, because what they mean is that there is another work that DiceBear's identicon is, well, based on.
