### ISSUE TITLE
styles for initials

### ISSUE THREAD

**Issue by johnsondani2010** [DiceBear/avatars#43]
How to change the initials styles to rounded one any thing available?

**Comment by FlorianKoerner** [comment]
Since the just released version 4.0.0 a radius can be defined for all avatars.

Example using the HTTP API:
https://avatars.dicebear.com/v2/initials/Florian%20K%C3%B6rner.svg?options[radius]=50

![](https://avatars.dicebear.com/v2/initials/Florian%20K%C3%B6rner.svg?options[radius]=50&options[width]=150)

Code example:

```js
import Avatars from '@dicebear/avatars';
import sprites from '@dicebear/avatars-initials-sprites';

let options = {
    radius: 50
};
let avatars = new Avatars(sprites, options);
let svg = avatars.create('Florian Körner');
```
