### ISSUE TITLE
Avatars Initials SVG in FF

### ISSUE THREAD

**Issue by Elardzhi** [DiceBear/avatars#63]
Initials are shifted down in Firefox.

**Comment by FlorianKoerner** [comment]
I can't reproduce it.

Do you have an example or a more specific version? I use version 75.0.

![Unbenannt](https://user-images.githubusercontent.com/647303/79017460-a94ae480-7b71-11ea-9d08-90f332bac384.PNG)

**Comment by Elardzhi** [comment]
Why did you close this issue? 
ok, if you are not interested in helping to fix your bugs I won't continue...

**Comment by FlorianKoerner** [comment]
@Elardzhi If you can give me more detailed information as requested and the problem can be reproduced, the ticket will of course be opened again.

But as long as no more detailed information is available and the problem cannot be reproduced by us, the ticket will remain closed. This is how we handle every ticket so that there are no dead tickets.

**Comment by FlorianKoerner** [comment]
See #69
