### ISSUE TITLE
Add .jpg / .png format

### ISSUE THREAD

**Issue by rayhantech** [DiceBear/avatars#77]

**Comment by FlorianKoerner** [comment]
There are already several libraries for conversion from SVG to JPG or PNG. A few examples are:

- https://github.com/lovell/sharp
- https://github.com/canvg/canvg

There will not be a built-in conversion for various reasons:

- We want to keep avatars as small as possible.
- Very few people need a conversion.
- Our API cannot offer conversion due to limitations of our cloud.
