### ISSUE TITLE
Self hosted api solution

### ISSUE THREAD

**Issue by elhmn** [DiceBear/avatars#79]
For some reason the api was down yesterday in Germany for about an hour, not sure what the reason for that was. And that led me to think that it would be nice if I could host the api on one of my servers. After checking the documentation I don't think I have found any information regarding that possibility. Is there any plan to provide a self hosted solution for the api in the future ?

And guyz thank you for this api and packages they are great ❤️ .

**Comment by FlorianKoerner** [comment]
Good morning from North Germany, Lübeck.

We use Cloudflare Workers to deliver the avatars worldwide fast and reliable. And we also use BunnyCDN to prevent known requests to the workers, which saves us a lot of money.

Yesterday there were problems with Cloudflare, which meant that all non-cached requests could not be answered.

See: https://www.cloudflarestatus.com/incidents/b888fyhbygb8

If you use the avatars on a website, I would recommend you to install the NPM packages and create the avatars directly on the website.

Otherwise you could develop a NodeJS server with express to create the avatars. Or you could use Cloudflare Workers like us.

**Comment by elhmn** [comment]
I see thanks. I was building an experimental project so I did not really consider generating the avatars directly on the user's web client, but will definitely do what you have suggested. Also the api has been very reliable in the past and will remain this way even after yesterday's incident I guess 🙇 .
