### ISSUE TITLE
Avataaaars in react native application

### ISSUE THREAD

**Issue by fbotalla** [DiceBear/avatars#87]
Male, female, human and a few other .svg work perfectly, but the avataaars only displays a box with the color of the hair/top of the avataaars. Is anyone else experiencing this?

`   <SvgUri
                                   width="200"
                                   height="200"
                                   source={{uri:"https://avatars.dicebear.com/api/avataaars/feee.svg?top[]=shortHair&topChance=40&hairColor[]=blonde"}}
                            />`

When I do I get a yellow mustard box.

**Comment by FlorianKoerner** [comment]
It seems to me that you use the library "react-native-svg-uri". And this is where I think the problem is. It seems that the library misinterprets a mask that the SVG.

Maybe you have more luck with the more popular library "react-native-svg"?
See: https://www.npmjs.com/package/react-native-svg#use-with-content-loaded-from-uri

I would be interested in the result. However, this is not a problem with Avatars, so I will close here for now.

**Comment by FlorianKoerner** [comment]
Seems to work with react-native-svg.

See: https://snack.expo.io/Rdi_J1gQM

![works](https://user-images.githubusercontent.com/647303/98446288-c736f280-211c-11eb-9ace-726f11289c43.PNG)

**Comment by fbotalla** [comment]
I see what you are saying. Thank you for the quick response. Interestingly enough it does work on Android but it does not work on iOS (using the library you suggested above).

**Comment by FlorianKoerner** [comment]
There is nothing wrong with the SVG. Here, a mask is simply not respected.

The good news is that we want to avoid masks in the future, which many libraries have problems with. There is already a ticket for this. See #48

**Comment by fbotalla** [comment]
Ok great! Thanks for the info! Do you know of a timeline when that will happen or it is just a thought for now?

**Comment by FlorianKoerner** [comment]
I think this will be completed in one to two weeks.

**Comment by FlorianKoerner** [comment]
@fbotalla With version 4.4.0 the problem seems to be fixed on iOS as well.
