### ISSUE TITLE
API is no longer works!

### ISSUE THREAD

**Issue by theMasix** [DiceBear/avatars#89]
Hello. Thanks for your great project.
I used this URL to generate ```avataaars``` until last night. But now it doesn't work anymore!
```url
https://avatars.dicebear.com/v2/avataaars/1.svg?top[]=shortHair&topChance=100&hairColor[]=platinum&hairColor[]=black&hairColor[]=blonde&hairColor[]=brown&hairColor[]=pastel&facialHair[]=light&facialHairColor[]=black&facialHairColor[]=brown&facialHairColor[]=gray&clothes[]=blazer&clothes[]=sweater&clothes[]=hoodie&clothesColor[]=white&clothesColor[]=blue&clothesColor[]=gray&clothesColor[]=heather&clothesColor[]=pastel&clothesColor[]=red&eyes[]=defaultValue&eyebrow[]=defaultValue&mouth[]=smile&skin[]=pale&skin[]=light
```
The error is:
![image](https://user-images.githubusercontent.com/22872117/98806412-6a924b00-242e-11eb-87db-fa21f4836a19.png)
---
I noticed that ```v2``` API is deprecated. So I changed ```v2``` to ```api``` but it didn't solve the problem.

**Comment by FlorianKoerner** [comment]
Hello @theMasix Thanks for your bug report.

It seems to me that it's the options you give. "defaultValue" is not a supported option.
If I remove defaultValue, it works.

https://avatars.dicebear.com/v2/avataaars/1.svg?top[]=shortHair&topChance=100&hairColor[]=platinum&hairColor[]=black&hairColor[]=blonde&hairColor[]=brown&hairColor[]=pastel&facialHair[]=light&facialHairColor[]=black&facialHairColor[]=brown&facialHairColor[]=gray&clothes[]=blazer&clothes[]=sweater&clothes[]=hoodie&clothesColor[]=white&clothesColor[]=blue&clothesColor[]=gray&clothesColor[]=heather&clothesColor[]=pastel&clothesColor[]=red&mouth[]=smile&skin[]=pale&skin[]=light

**Comment by theMasix** [comment]
Thanks for your answer. Yes 
Is the ```defaultValue``` removed recently? I could get the avatar until last night.
I don't see anything about ```defaultValue``` in past few month at [Releases](https://github.com/DiceBear/avatars/releases) page.

And another question, If I remove ```defaultValue```, my avatars are different from previous one. How can I avoid it?

**Comment by FlorianKoerner** [comment]
I have updated my answer. It responds to your questions. "defaultValue" was actually never a allowed value and was simply ignored in the past.

However, since an update last night it is no longer. "defaultValue" simply has to be exchanged with "default".

**Comment by theMasix** [comment]
Yeah. It's corrected now!
![image](https://user-images.githubusercontent.com/22872117/98810692-d5df1b80-2434-11eb-9799-520aa023d021.png)
Thanks for your instant response and actions!

**Comment by FlorianKoerner** [comment]
<img width="387" alt="Bildschirmfoto 2020-11-11 um 13 14 09" src="https://user-images.githubusercontent.com/647303/98810631-cbfeed80-241f-11eb-93e0-ec933e3f157c.png">

Error in the generator is now fixed.

Valid are always the values from the readme.
https://github.com/DiceBear/avatars/blob/v4/packages/avatars-avataaars-sprites/README.md

**Comment by FlorianKoerner** [comment]
> my avatars are different from previous one. How can I avoid it?

This can happen from time to time with the API, because the API always uses the latest version of avatars. Newer versions have among other things new options and therefore the result can look different. But this does not happen too often.

If you want to make sure that the same avatar will be created in the future, you have to make sure that you always use the same version. Unfortunately, you can only do this by installing via NPM.

Translated with www.DeepL.com/Translator (free version)

**Comment by FlorianKoerner** [comment]
my avatars are different from previous one. How can I avoid it?

This can happen from time to time with the API, because the API always uses the latest version of avatars. Newer versions have among other things new options and therefore the result can look different. But this does not happen too often.

If you want to make sure that the same avatar will be created in the future, you have to make sure that you always use the same version. Unfortunately, you can only do this by installing via NPM.

**Comment by theMasix** [comment]
I think the correct approach would be to make the API accessible in different versions like before (v2, v3 etc). And In each version the API should always return the same result. Do you have any limitation on creating multiple version of API?

**Comment by FlorianKoerner** [comment]
This is also the plan for the future. But before that, there is still some work to be done. Our serverless architecture allows only scripts of 1MB and only 50 in number.

So I'm in the process of reducing the dependencies, so that all avatar styles can be in one script. Then we can theoretically offer up to 50 versions via the API.

Currently we are limited due to the size of avatars and offer only one version via the API.

I think at the beginning of next year it will be ready.

**Comment by FlorianKoerner** [comment]
By the way, the old versioning of the API did not refer to the used avatars version. It was due to the change from PNG to SVG.

**Comment by theMasix** [comment]
Great. You have the right plan. Also You can use something like Netlify or Vercel if you need more resources for the API. Good Luck

**Comment by FlorianKoerner** [comment]
Versioning is now supported.
https://avatars.dicebear.com/docs/http-api#versioning

**Comment by theMasix** [comment]
Yeah! I was going remove DiceBear avataars from my whole project! This versioning saved package.
