### ISSUE TITLE
Wrong type error on background attributes.

### ISSUE THREAD

**Issue by wushan** [DiceBear/avatars#95]
Hi,
According to the document, assigning a background color is using 2 `[]` which is type array.
```
https://avatars.dicebear.com/4.4/v2/human/Sugar%2077toby%20dadddy.svg?options[background][]=%23333333
```
but when accessing the url above, we'll get a type error now.

```
background must be a `string` type, but the final value was: `[
  "\"#333333\""
]`.
```

Is this a breaking change which not mentioned in the document ?

**Comment by FlorianKoerner** [comment]
`background` has always been a string. We have not changed anything. Maybe the test is just a bit stricter now.
You come from sabai99, right? Because there I could see exactly this problem. Not with other referrers actually.

Because of the repeated error the page was blocked yesterday. I have just unblocked the page. Please take care of a quick fix on your part.

This works:
https://avatars.dicebear.com/4.4/v2/human/Sugar%2077toby%20dadddy.svg?options[background]=%23333333

We are currently in version 4.4. Here you can see in the documentation of 4.0 that a background could never be an array:
https://www.npmjs.com/package/@dicebear/avatars-human-sprites/v/4.0.0
